spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolDb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


school:
  app:
    jwtSecret: GtFPkqzKAbks8cswXPXN


server:
  error:
    include-message: always

